module.exports = [
    {
        src:[
            './build/validate/validate.js',
            './build/js/plugin/**',
            './build/js/common/**',
        ],
        concatName:'main.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/validate/sub/permission.js',
            './build/js/ui/permission-menu.js',
            './build/js/page/permission/**.js'
        ],
        concatName:'permission.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/validate/sub/permission.js',
            './build/js/ui/permission-menu.js',
            './build/js/page/permission/admin/**'
        ],
        concatName:'permission-admin.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/validate/sub/permission.js',
            './build/js/ui/permission-menu.js',
            './build/js/page/permission/merchant/**'
        ],
        concatName:'permission-merchant.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/ws-login.js',
        ],
        concatName:'ws-login.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/qrcode.js',
            './build/js/ui/qrcode-login.js',
        ],
        concatName:'qrcode-login.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/common/md5.js',
            './build/js/page/login/supersized.3.2.7.min.js',
            './build/js/page/login/supersized-init.js',
            './build/js/page/login/scripts.js',
        ],
        concatName:'login.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/wx.js',
        ],
        concatName:'wx.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/product/list.js',
        ],
        concatName:'product.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/bootstrap-datetimepicker.min.js',
            './build/js/ui/date.js',
            './build/js/page/order/list.js',
        ],
        concatName:'order.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/bootstrap-datetimepicker.min.js',
            './build/js/ui/date.js',
            './build/js/page/order/seat.js',
        ],
        concatName:'order-seat.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/bootstrap-datetimepicker.min.js',
            './build/js/ui/date.js',
            './build/js/page/order/rate.js',
        ],
        concatName:'order-rate.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/withdraw/index.js',
        ],
        concatName:'withdraw.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/ui/bootstrap-datetimepicker.min.js',
            './build/js/ui/date.js',
            './build/js/page/withdraw/list.js',
        ],
        concatName:'withdraw-list.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/withdraw/bank.js',
        ],
        concatName:'withdraw-bank.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/member/group.js',
        ],
        concatName:'member-group.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/member/list.js',
        ],
        concatName:'member-list.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/member/spread.js',
        ],
        concatName:'member-spread.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/merchant/activity.js',
        ],
        concatName:'merchant-activity.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/merchant/music.js',
        ],
        concatName:'merchant-music.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/merchant/team.js',
        ],
        concatName:'merchant-team.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/message/get.js',
        ],
        concatName:'message-get.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/message/send.js',
        ],
        concatName:'message-send.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/message/order.js',
        ],
        concatName:'message-order.js',
        destPath:'./build/js/build/'
    },
    {
        src:[
            './build/js/page/spread/index.js',
        ],
        concatName:'spread.js',
        destPath:'./build/js/build/'
    },
];